config/routes.rb
Videoquest::Application.routes.draw do
  
  resources :videos do 
    resources :comments    
  end
  
  get "log_out" => "Sessions#destroy", :as => "log_out"
  get "log_in" => "Sessions#new", :as => "log_in"
  get "sign_up" => "Users#new", :as => "sign_up"
  
  
  resources :users
  resources :sessions

  
  root :to => 'Videos#index'
  
  

  
  

  
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :video
  
  validates_presence_of :user
  validates_presence_of :video
end

app/models/user.rb
class User < ActiveRecord::Base
  
  attr_accessible :email, :password, :password_confirmation
  attr_accessor :password
  before_save :encrypt_password
  
  
  validates_confirmation_of :password
  validates_presence_of :password, :on => :create
  validates_presence_of :email
  validates_uniqueness_of :email 
  validates_format_of :email, :with => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i, :on => :create
  
  has_many :comments
  has_many :videos
  
  def self.authenticate(email, password)
    user = User.find_by_email(email)
    if user && user.password_hash == BCrypt::Engine.hash_secret(password, user.password_salt)
      user
    else
      nil
    end
  end
  
  def encrypt_password 
    if password.present?
      self.password_salt = BCrypt::Engine.generate_salt
      self.password_hash = BCrypt::Engine.hash_secret(password, password_salt)    
    end
  end
  
end

app/models/video.rb
class Video < ActiveRecord::Base
  attr_accessible :user_id, :path, :about
  has_many :comments #dependent: :destroy
  belongs_to :user
  
  validates_presence_of :user
  validates_presence_of :path
    
  mount_uploader :path, VideoUploader
  
  def transcode_flv
    IO.popen("ffmpeg -y -i #{[Rails.root,'/public', self.path.to_s].join} -ar 11025 -f flv #{['public', self.path.to_s, ".flv"].join}")
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  helper_method :current_user
  
  private 
  
  def current_user
    @current_user = User.find(session[:user_id]) if session[:user_id]
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  
  before_filter :get_video
  
  def get_video
    @video = Video.find(params[:video_id])
  end
 
  def new
    @comment = Comment.new
  end
  
  def create
    @comment = @video.comments.new(params[:comment])
    @comment.user = current_user
    if @comment.save
      redirect_to root_url, :notice => "Comment added"
    else
      render "new"   
    end
  end
  
  def index
    @comments = @video.comments.all 
    respond_to do |format|
      format.html
    end
  end
  
  def destroy
    @comment = Comment.find(params[:id])
    if @comment.user == current_user
      @comment.destroy
      redirect_to root_url
      else
        redirect_to root_url, :notice => "Comment belongs to another user"    
    end
    
  end
 
  def show
    @comments = @video.comments.all
    respond_to do |format|
      format.html
    end
   end
  
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end
  
  def create
    user = User.authenticate(params[:email], params[:password])
    if user
      session[:user_id] = user.id
      redirect_to root_url, :notice => "Logged in!"
    else
      flash.now.alert = "Invalid email or password"
      render "new"
    end
  end
  
  def destroy
     session[:user_id] = nil
     redirect_to root_url, :notice => "Logged out!"   
  end
    
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end
  
  def create
    @user = User.new(params[:user])
    @user.email.downcase
    if @user.save
      redirect_to root_url, :notice => "Signed Up!"
     else
       render "new"
    end 
  end
 

end

app/controllers/videos_controller.rb
class VideosController < ApplicationController
  
  def new
    @video = Video.new
  end
  
  def create
    @video = Video.new(params[:video])
    @video.user = current_user
    
    if @video.save
      @video.delay.transcode_flv
      redirect_to root_url, :notice => "Video saved"
    else
      render "new"
    end

  end

  def index
    @videos = Video.all 
    respond_to do |format|
      format.html
    end
  end
  
  def show
    @video = Video.find(params[:id])
    respond_to do |format|
      format.html
    end
  end
  
  #DELETE /Videos/1
  def destroy
    @video = Video.find(params[:id])
    if @video.user == current_user
      @video.destroy
      respond_to do |format|
        format.html { redirect_to root_url}
      end
    else
      redirect_to root_url, :notice => "video belongs to another user"      
    end

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/videos_helper.rb
module VideosHelper
end

app/views/comments/_comment.html.erb
<%= div_for comment do%>
	<p> Postet by <%= comment.user.email %>, <%= time_ago_in_words comment.created_at %> ago</p>
	<p> <%= comment.comment_text %> </p>
<% end %>

app/views/comments/index.html.erb
<h1>Comments#index</h1>

<div id="comments">
	<%= render @comments%>
</div>

app/views/comments/new.html.erb
<h1>Comments#new</h1>

<%= form_for([@video, @comment]) do |f| %>
	<% if @comment.errors.any? %>
	<div class="error_messages">
		<h2>Form is invalid</h2>
		<ul>
			<% for message in @comment.errors.full_messages %>
			<li><%= message %></li>
			<% end %>
		</ul>
	</div>
	<% end %>
	<p>
		<%= f.label :comment_text %> <br />
		<%= f.text_area :comment_text %>
	</p>
	<p class="button"><%= f.submit %></p>
<%end%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Videoquest</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
	<div id="site_nav">
		<%= link_to "Видео", videos_path %>
		<%= link_to 'Новое видео', new_video_path %>
	</div>
	<div id="user_nav">
		<% if current_user %>
			<%= current_user.email %>
			<%= link_to "Выйти", log_out_path %>		
		<% else %>
			<%= link_to "Войти", log_in_path %> или
			<%= link_to "Зарегистрироваться", sign_up_path %>		
		<% end %>
	</div>
	
	<% flash.each do |name, msg| %>
		<%= content_tag :div, msg, :id => "flash_#{name}" %>
	<% end %>
	
	<%= yield %>

</body>
</html>

app/views/users/new.html.erb
<h1>Sign Up</h1>

<%= form_for @user do |f| %>
	<% if @user.errors.any? %>
	<div class="error_messages">
		<h2>Form is invalid</h2>
		<ul>
			<% for message in @user.errors.full_messages %>
			<li><%= message %></li>
			<% end %>
		</ul>
	</div>
	<% end %>
	
	<p> 
		<%= f.label :email %> <br />
		<%= f.text_field :email%>
	</p>
	<p> 
		<%= f.label :password %> <br />
		<%= f.text_field :password %>
	</p>
	<p> 
		<%= f.label :password_confirmation %> <br />
		<%= f.text_field :password_confirmation%>
	</p>
	
	<p class="button"><%= f.submit%></p>
<% end %>
	

app/views/videos/_video.html.erb
<%= div_for video do %>
	<div class="about">
		<p>Видео добавленно <%= video.user.email %>, <%= video.about %></p>		
		<%= link_to 'show' , video %>
				<%= link_to 'delete', video, method: :delete %>

	</div>
	
	<div class="comments">	
		<div class="last_comments">
			<p>Последние коментарии:</p>
			
			<% video.comments.order(:created_at).reverse_order.limit(3).each do |comment| %>
				<%= render comment %>
			<% end %>
		</div>
		
		<%= link_to "Все комментарии(#{video.comments.count})", video_comments_path(video) %>
		<%= link_to 'Добавить комментарий', new_video_comment_path(video) %>
	</div>
	
	<object id="flowplayer" type="application/x-shockwave-flash" width="400" height="320">
    	<param name="movie" value="flowplayer-3.2.10.swf" /> 
    	<param name="flashvars" value='config={"clip":{"url":"<%= video.path.to_s %>.flv", "autoPlay": false}},' />	
    </object>
    
	
<% end %>

app/views/videos/index.html.erb
<h1>Videos#index</h1>

<div id="videos">
	<%= render @videos %>
</div>

app/views/videos/new.html.erb
<h1>Videos#new</h1>

<%= form_for @video, :html => {:multipart => true} do |f| %>
	<% if @video.errors.any? %>
	<div class="error_messages">
		<h2>Form is invalid</h2>
		<ul>
			<% for message in @video.errors.full_messages %>
			<li><%= message %></li>
			<% end %>
		</ul>
	</div>
	<% end %>
	<p>
		<%= f.label :about %> <br />
		<%= f.text_field :about %>
	</p>
	<p>
		<%= f.label :path %> <br />	
		<%= f.file_field :path %>	
	</p>
	
	<p class="button"><%= f.submit %></p>
<%end%>

app/views/videos/show.html.erb
<%= render @video %>